---

- name: Generate database credentials
  set_fact:
    zabbix_admin_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=12') }}"
    zabbix_mysql_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=20') }}"
    root_mysql_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=24') }}"

- name: Template MySQL query to update Zabbix web administrator password and disable guests
  template:
    src: zabbix_admin.sql.j2
    dest: /usr/share/doc/zabbix-server-mysql/zabbix_admin.sql
    owner: root
    group: root
    mode: 0400
  register: admindb

- name: Set Zabbix web administrator password and disable guests using generated MySQL script
  mysql_db:
    name: zabbix
    target: /usr/share/doc/zabbix-server-mysql/zabbix_admin.sql
    state: import
  when: zabbix_admin_password is defined and admindb is changed

- name: Template Zabbix web administrator password to a file for user reference later
  template:
    src: zabbix_admin_password.j2
    dest: /root/zabbix_admin_password
    owner: root
    group: root
    mode: 0600
  when: zabbix_admin_password is defined

- name: Create MySQL user account for Zabbix
  mysql_user:
    name: zabbix
    password: "{{ zabbix_mysql_password }}"
    priv: 'zabbix.*:ALL'
    state: present
  when: zabbix_mysql_password is defined

- name: Set MySQL root password
  mysql_user:
    check_implicit_admin: yes
    name: root
    host_all: yes
    password: "{{ root_mysql_password }}"
  when: root_mysql_password is defined

- name: Template my.cnf configuration file
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600
  when: root_mysql_password is defined

- name: Configure Zabbix server daemon to use MySQL credentials
  replace:
    path: /etc/zabbix/zabbix_server.conf
    regexp: '^# DBPassword='
    replace: "DBPassword={{ zabbix_mysql_password }}"
  no_log: True
  when: zabbix_mysql_password is defined
  notify:
    - restart zabbix-server

- name: Configure Zabbix web interface to use MySQL credentials
  template:
    src: web_zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    owner: root
    group: www-data
    mode: 0640
  when: zabbix_mysql_password is defined
