---

- name: Install needed MySQL Python module package
  apt:
    name: python-mysqldb
    state: latest
    update_cache: yes
  tags:
    - apt
    - packages

- name: Remove all anonymous MySQL user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: Remove MySQL test database
  mysql_db:
    name: test
    state: absent

- name: Create MySQL database for Zabbix
  mysql_db:
    name: zabbix
    collation: utf8_bin
    encoding: utf8
    state: present
  register: createdb

- name: Import Zabbix database schema
  mysql_db:
    name: zabbix
    collation: utf8_bin
    encoding: utf8
    target: /usr/share/doc/zabbix-server-mysql/create.sql.gz
    state: import
  when: createdb is changed

- name: Generate passwords
  set_fact:
    zabbix_admin_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=12') }}"
    zabbix_mysql_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=20') }}"
    root_mysql_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=24') }}"
  when: createdb is changed

- name: Template MySQL query to update Zabbix web administrator password and disable guests
  template:
    src: zabbix_admin.sql.j2
    dest: /usr/share/doc/zabbix-server-mysql/zabbix_admin.sql
    owner: root
    group: root
    mode: 0400
  when: createdb is changed

- name: Template MySQL query to update Zabbix mail server
  template:
    src: zabbix_media.sql.j2
    dest: /usr/share/doc/zabbix-server-mysql/zabbix_media.sql
    owner: root
    group: root
    mode: 0400
  when: createdb is changed
  register: storemail

- name: Template MySQL query to implement Slack media
  template:
    src: zabbix_slack.sql.j2
    dest: /usr/share/doc/zabbix-server-mysql/zabbix_slack.sql
    owner: root
    group: root
    mode: 0400
  when: createdb is changed
  register: slackdb

- name: Set Zabbix web administrator password and disable guests using generated MySQL script
  mysql_db:
    name: zabbix
    target: /usr/share/doc/zabbix-server-mysql/zabbix_admin.sql
    state: import
  when: createdb is changed
  register: setzabbixweb

- name: Template Zabbix web administrator password to a file for user reference later
  template:
    src: zabbix_admin_password.j2
    dest: /root/zabbix_admin_password
    owner: root
    group: root
    mode: 0600
  when: setzabbixweb is changed

- name: Configure the local mail server that Zabbix should use
  mysql_db:
    name: zabbix
    target: /usr/share/doc/zabbix-server-mysql/zabbix_media.sql
    state: import
  when: storemail is changed

- name: Implement Slack media within Zabbix database
  mysql_db:
    name: zabbix
    target: /usr/share/doc/zabbix-server-mysql/zabbix_slack.sql
    state: import
  when: slackdb is changed

- name: Create MySQL user account for Zabbix
  mysql_user:
    name: zabbix
    password: "{{ zabbix_mysql_password }}"
    priv: 'zabbix.*:ALL'
    state: present
  when: zabbix_mysql_password is defined

- name: Set MySQL root password
  mysql_user:
    check_implicit_admin: yes
    name: root
    host_all: yes
    password: "{{ root_mysql_password }}"
  when: root_mysql_password is defined

- name: Template my.cnf configuration file
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600
  when: root_mysql_password is defined

- name: Configure Zabbix server daemon to use MySQL credentials
  replace:
    path: /etc/zabbix/zabbix_server.conf
    regexp: '^# DBPassword='
    replace: "DBPassword={{ zabbix_mysql_password }}"
  no_log: True
  when: zabbix_mysql_password is defined
  notify:
    - restart zabbix-server

- name: Configure Zabbix web interface to use MySQL credentials
  template:
    src: web_zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    owner: root
    group: www-data
    mode: 0640
  when: zabbix_mysql_password is defined
