---

- name: Install needed MySQL Python module package
  apt:
    name: python-mysqldb
    state: latest

- name: Remove all anonymous MySQL user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: Remove MySQL test database
  mysql_db:
    name: test
    state: absent

- name: Create MySQL database for Zabbix
  mysql_db:
    name: zabbix
    collation: utf8_bin
    encoding: utf8
    state: present
  register: createdb

- name: Import Zabbix database schema
  mysql_db:
    name: zabbix
    collation: utf8_bin
    encoding: utf8
    target: /usr/share/doc/zabbix-server-mysql/create.sql.gz
    state: import
  when: createdb is changed
  register: importdb

- name: Include additional database tasks, when needed
  include: "{{ item }}.yaml"
  loop:
    - credentials
    - mail
    - slack
  when: importdb is changed
