---

- name: Ensure that ufw package is installed
  apt:
    name: ufw
    state: latest
    update_cache: yes
  tags:
    - apt
    - packages

- name: Allow all inbound traffic on localhost interface
  ufw:
    rule: allow
    interface: lo
    direction: in

- name: Allow Zabbix agent access to Zabbix server
  ufw:
    rule: allow
    port: 10051
    proto: tcp

- name: Open SNMP trap port
  ufw:
    rule: allow
    port: 162
    proto: udp

- name: Allow SSH access 
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Allow HTTP and HTTPS access to Apache
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 80
    - 443

- name: Set default ufw policy to reject
  ufw:
    state: enabled
    policy: reject
