---

- name: Ensure that ufw package is installed
  apt:
    name: ufw
    state: latest
    update_cache: yes

- name: Allow all traffic on localhost interface
  ufw:
    rule: allow
    interface: lo

- name: Allow access to Zabbix
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items: [ 10050, 10051 ]

- name: Open SNMP trap port
  ufw:
    rule: allow
    port: 162
    proto: udp

- name: Allow SSH access 
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Allow HTTP and HTTPS access to Apache
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items: [ 80, 443 ]

- name: Set default outbound ufw policy to allow
  ufw: 
    direction: out
    policy: allow

- name: Set default inbound ufw policy to deny
  ufw:
    direction: in
    policy: deny

- name: Reload ufw
  ufw:
    state: reloaded
