---

- name: Install Apache and PHP packages
  apt:
    name: "{{ web_packages }}"
    state: latest
  vars:
    web_packages:
    - apache2
    - libapache2-mod-php7.2

- name: Replace default Apache index for installation process
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: Install official Certbot package repository (PPA)
  apt_repository:
    repo: ppa:certbot/certbot

- name: Install Certbot from their package repository (PPA)
  apt:
    name: "{{ certbot_packages }}"
    state: latest
  vars:
    certbot_packages:
    - certbot
    - python3-certbot-apache

- name: Remove unnecessary Apache configuration symbolic links
  file:
    path: "/etc/apache2/conf-enabled/{{ item }}.conf"
    state: absent
  loop:
    - other-vhosts-access-log
    - serve-cgi-bin
  notify:
    - reload apache2

- name: Enable Apache headers module
  command: a2enmod headers
  args:
    creates: /etc/apache2/mods-enabled/headers.load
  notify:
    - reload apache2

- name: Template Apache security configuration file
  template:
    src: security.conf.j2
    dest: /etc/apache2/conf-available/security.conf
  notify:
    - reload apache2

- name: Template Apache Zabbix virtual host configuration file (without enabling)
  template:
    src: zabbix.conf.j2
    dest: /etc/apache2/sites-available/zabbix.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload apache2
