---

- name: Create default Apache document root
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  loop:
    - /var/www
    - /var/www/html

- name: Replace default Apache index during installation process
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: Install Zabbix package repository
  apt:
    deb: 'https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+bionic_all.deb'

- name: Install Zabbix packages
  apt:
    name: "{{ zabbix_packages }}"
    state: latest
    update_cache: yes
  vars:
    zabbix_packages:
    - zabbix-agent
    - zabbix-server-mysql
    - zabbix-frontend-php

- name: Configure Zabbix agent to only expect local connections
  replace:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^# ListenIP=0.0.0.0'
    replace: 'ListenIP=127.0.0.1'
  notify:
    - restart zabbix-agent

- name: Secure ownership and permissions of Zabbix server configuration file
  file:
    path: /etc/zabbix/zabbix_server.conf
    owner: root
    group: zabbix
    mode: 0640

- name: Run mail server role
  include_role:
    name: mail

- name: Check for my.cnf configuration file
  stat:
    path: /root/.my.cnf
  register: mycnf

- name: Run MySQL role if it has not already been done
  include_role:
    name: mysql
  when: not mycnf.stat.exists

- name: Check for Zabbix web virtual host configuration file
  stat:
    path: /etc/apache2/sites-available/zabbix.conf
  register: vhost

- name: Run web role if it has not already been done
  include_role:
    name: web
  when: not vhost.stat.exists

- name: Ensure that Zabbix server starts at boot
  command: systemctl enable zabbix-server
  args:
    creates: /etc/systemd/system/multi-user.target.wants/zabbix-server.service

- name: Ensure that Zabbix agent starts at boot
  command: systemctl enable zabbix-agent
  args:
    creates: /etc/systemd/system/multi-user.target.wants/zabbix-agent.service

- name: Run ufw/firewall role
  include_role:
    name: ufw

- name: Template Zabbix web access instructions for root user
  template:
    src: zeromon.access.j2
    dest: /root/.zeromon
    owner: root
    group: root
    mode: 0600

- name: Template root user shell profile to include Zabbix access instructions
  template:
    src: root.profile.j2
    dest: /root/.profile
    owner: root
    group: root
    mode: 0644
