---

- name: Configure Zabbix agent to only expect local connections
  replace:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^# ListenIP=0.0.0.0'
    replace: 'ListenIP=127.0.0.1'
  notify:
    - restart zabbix-agent

- name: Secure ownership and permissions of Zabbix server configuration file
  file:
    path: /etc/zabbix/zabbix_server.conf
    owner: root
    group: zabbix
    mode: 0640

- name: Template alertscript for optional Slack notifications
  template:
    src: slack.sh.j2
    dest: /usr/lib/zabbix/alertscripts/slack.sh
    owner: root
    group: zabbix
    mode: 0750

- name: Ensure that Zabbix server starts at boot
  command: systemctl enable zabbix-server
  args:
    creates: /etc/systemd/system/multi-user.target.wants/zabbix-server.service

- name: Ensure that Zabbix agent starts at boot
  command: systemctl enable zabbix-agent
  args:
    creates: /etc/systemd/system/multi-user.target.wants/zabbix-agent.service

- name: Template Zabbix web access instructions for root user
  template:
    src: zeromon.access.j2
    dest: /root/.zeromon
    owner: root
    group: root
    mode: 0600

- name: Template root user shell profile to include Zabbix access instructions
  template:
    src: root.profile.j2
    dest: /root/.profile
    owner: root
    group: root
    mode: 0644

- name: Remove unnecessary Zabbix Apache configuration file
  file:
    path: /etc/apache2/conf-enabled/zabbix.conf
    state: absent
  notify:
    - reload apache2

- name: Remove default Apache virtual host symbolic link
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify:
    - reload apache2

- name: Enable Zabbix Apache virtual host
  file:
    src: /etc/apache2/sites-available/zabbix.conf
    dest: /etc/apache2/sites-enabled/zabbix.conf
    state: link
  notify:
    - reload apache2
